name: mischa
favicon: null
layout_spectrum: 0.25543
typography_spectrum: 0.31219
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.7009882126003504
  lightness: 0.7229423525277525
  saturation: 0.6371285645291209
  rhythmicContrast: 0.3909640747588128
purpose: []
